# Stage 1: Restore & Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copy toàn bộ source vào image
COPY ./TicketService /app/TicketService
COPY ./DatabaseModels /app/DatabaseModels/

# Restore dependencies
WORKDIR /app/TicketService
RUN dotnet restore

# Build
RUN dotnet publish -c Release -o /app/publish

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "TicketService.dll"]